### ISSUE TITLE
Quantum moon orbit position occupied! Aborting collapse.

### ISSUE THREAD

**Issue by nice2cu1** [hearth1an/hearth1an.Origins#2]
mod version: v1.0.4
No matter how I turn on the light,turn off the light,Quantum moon still locked on a planet
The following are the mods I have enabled:
![image](https://github.com/hearth1an/hearth1an.Origins/assets/33564254/c37d0bb1-5182-4546-b2ff-58c02a2545f3)

**Comment by Espuma1** [comment]
Also experiencing this issue - the log shows the message [Quantum moon orbit position occupied! Aborting collapse] constantly

**Comment by Espuma1** [comment]
I'm not quite sure how the moon's positioning is programmed, but I have yet to see it reach Dark Bramble outside of the first loop. Maybe it gets stuck when it tries to send the moon to bramble?

**Comment by hearth1an** [comment]
Last time I was checking it before pushing the update - everything was okay. Could you provide more information with exact steps     that leads to this error?  I can't reproduce it unfortunately, here's my steps:
1. Wake up
2. Go to the DB state of QM
3. Go to it's north pole
4. Get seed signal.

I just reinestalled everything and started a new game, didn't encounter such bug

**Comment by nice2cu1** [comment]
@hearth1an This problem occurred in the cycle after I got the seed signal, because the signal was obtained at the North Pole, so I wanted to go to the North Pole of the DB through QM, and this problem was triggered in this case, no matter what I was On the QM or in space, changing the position of the QM multiple times will cause this problem: the position of the QM will not change again, it will always be locked at the place where it was last seen

**Comment by hearth1an** [comment]
Ok I'll take a look at this, thanks! Btw you don't need to do that every time. Once you got the signal known, you can go straight to the secret section of Dark Bramble (Dark Bramble will look like this)
![image](https://github.com/hearth1an/hearth1an.Origins/assets/106444732/8d2b0bcd-8d65-4654-ae7e-13e39788bf05)

**Comment by ThomasMiz** [comment]
Hello! I am having this same issue times a million. I mean a literal million, enough log events that the logger ran out of memory 🤣

<img width="410" alt="image" src="https://github.com/hearth1an/hearth1an.Origins/assets/32400648/cecef3ba-a89d-4fc5-a136-ddbf1d4e72f2">

No other mods aside this one (and its dependencies recursively) are installed.

I've been able to consistently reproduce the bug like so:
1. Go to the quantum moon. The location of the quantum moon doesn't matter.
2. Head to its north pole. You'll have to get into a quantum shrine and change into another location (such as Giant's Deep) to cross the equator, and then another (such as Timber Hearth) to get a location where the shrine can appear in the north pole.
3. Get the quantum shrine to appear in the north pole, enter it with your flashlight turned on and close the door. Once the door is closed, turn off your flash light and then turn it back on.

The location of the moon changes as expected, but if I turn the flashlight off and on again, nothing happens. If I open and exit the shrine, get it to disappear and reappear somewhere else, then get in and try again, still nothing happens.

I get off the quantum moon, into space, get 6km away from the quantum moon and start spinning around trying to get it to change location, it does not. I open and close the map multiple times, but the moon refuses to move at all. The scout was with my this whole time by the way, I had no picture taken.

Is there any workaround so I can still play this?
